<a href="https://colab.research.google.com/github/MonikaRGaikwad/DataScience/blob/main/BuyerRatio_Assgn3_Q_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.


In [ ]:
import pandas as pd
from scipy import stats as stats
import numpy as np

In [ ]:
df= pd.read_csv('/content/BuyerRatio..csv')

In [ ]:
df.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   550   351    480    350

In [ ]:
df_table=df.iloc[:,1:6]

In [ ]:
df_table

East  West  North  South
0    50   142    131     70
1   550   351    480    350

In [ ]:
df_table.values


array([[ 50, 142, 131,  70],
       [550, 351, 480, 350]])

In [ ]:
val=stats.chi2_contingency(df_table)


In [ ]:
val

(80.27295426602495,
 2.682172557281901e-17,
 3,
 array([[111.01694915,  91.21892655, 113.05225989,  77.71186441],
        [488.98305085, 401.78107345, 497.94774011, 342.28813559]]))

In [ ]:
type(val)


tuple

In [ ]:
no_of_rows=len(df_table.iloc[0:2,0])
no_of_columns=len(df_table.iloc[0,0:4])
degree_of_f=(no_of_rows-1)*(no_of_columns-1)
print('Degree of Freedom=',degree_of_f)


Degree of Freedom= 3


In [ ]:
Expected_value=val[3]


In [ ]:
Expected_value

array([[111.01694915,  91.21892655, 113.05225989,  77.71186441],
       [488.98305085, 401.78107345, 497.94774011, 342.28813559]])

In [ ]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(df_table.values,Expected_value)])
chi_square_statestic=chi_square[0]+chi_square[1]
chi_square_statestic

75.83769204761725

In [ ]:
critical_value=chi2.ppf(0.95,3)
critical_value

7.814727903251179

In [ ]:
if chi_square_statestic >= critical_value:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')


Dependent (reject H0)


In [ ]:
pvalue=1-chi2.cdf(chi_square_statestic,3)
pvalue

2.220446049250313e-16

In [ ]:
if pvalue <= 0.05:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')


Dependent (reject H0)


In [ ]:
no_of_columns


4

In [ ]:
no_of_rows

2

In [ ]:
df_table=pd.crosstab(df['East'],df['Observed Values'])
df_table

Observed Values  Females  Males
East                           
50                     0      1
550                    1      0

In [ ]:
df_table.values


array([[0, 1],
       [1, 0]])